[repository]
name = "winctl"
authors = ["you"]

[winctl]
description = "Native resize/center/snap/expand window dispatchers for Hyprland"
authors = ["you"]
output = "winctl.so"
build = [
    "make all"
]
